cmake_minimum_required(VERSION 2.8)

find_package(Boost REQUIRED COMPONENTS thread regex)
find_package(APR REQUIRED)
find_package(APACHE REQUIRED)
find_package(CURL REQUIRED)
find_package(JsonCPP)
find_package(PnsJsonCPP)
if ( NOT JSONCPP_FOUND AND NOT PNS_JSONCPP_FOUND )
  message(FATAL_ERROR "Package jsoncpp or pns-jsoncpp is required, but not found!")
endif()

include_directories(${Boost_INCLUDE_DIRS})
include_directories(${APR_INCLUDE_DIR})
include_directories(${APACHE_INCLUDE_DIR})
include_directories(${CURL_INCLUDE_DIR})
